### ISSUE TITLE
[TODO] 대신 정해주기 기능 

### ISSUE THREAD

**Issue by yunjin-kim** [code-etc/code-etc-worldcup-frontend#5]
- [x] msw를 통한 더미 데이터 생성  fb648f97db445cbfa93dccbcf8185fadd1fcae3b
- [x] 대신 정해주기 두 개의 후보자들 렌더링 e21fca71fcbdc3d634530bc8c33c969ac24adace
- [x] 대신 정해주기 결과 렌더링 d29523c3fec7990043355ce3ebc4f04d5de5b4b6
- [x] 대신 정해주기 후보자들 이미지 최적화 df2ada42df0deb7bc852f9b57d53b11d1889a705
- [ ] 대신 정해주기 선택시 UI 이벤트

**Comment by yunjin-kim** [comment]
2020/02/17 회의 피드백
- [x] Layout 규격 ff38ee97df3e33f9e77416c4563b2a68375ad876
- [x] 폰트 적용 3e09b07cfe9ac05d0f6952e1035223dce84e6193
- [x] 마우스 호버 이벤트 ff38ee97df3e33f9e77416c4563b2a68375ad876
