### ISSUE TITLE
[TODO] 월드컵 게임 기능

### ISSUE THREAD

**Issue by yunjin-kim** [code-etc/code-etc-worldcup-frontend#8]
- [x] 월드컵 게임 msw 더미 데이터 9eea25d940391804530b4da290dcc36973465af6
- [x]  월드컵 게임 결과를 보여주는 기능 bbccae453aeff10da9ced2a009b1955adfa78e56
- [x] 월드컵 게임 후보자들 보여주고 선택하는 기능 b19167841c49f94498ff8d814a0f0cb21d69e7d6
- [x] 월드컵 부전승 생성시 부전승 후보자 선택하는 기능 83f57b2bbb5d38ae184333a6835d6c9f3f8770dd

**Comment by yunjin-kim** [comment]
2022/02/19 회의 피드백
- [x] 사진 비율에 따라 여백이 커질 수 있어 사진 높이 중앙 정렬 c26a790b3a835702b7f275177bf086d07195a127
- [x] 글자 잘 보이게 c26a790b3a835702b7f275177bf086d07195a127

**Comment by yunjin-kim** [comment]
2022/02/23 회의 피드백
- [x] 후보자 설명 클릭 이벤트 추가 8ca047edfc76c45adacfecdde698f7185b863aee
